In [ ]:
# numpy and basics
import numpy as np

#python List
list=[1,2,3]
print(list*2)

#numpy array
arr=np.array(list)
print(arr*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
import numpy as np

#this is 1d array
arr=np.array([1,2,3,4])

print(arr)

#2d array

matrix = np.array(([1,2,3],
                  [4,5,6]))
print(matrix)

 #array properteis (basic maniplation)

#print(arr.ndim)
#print(arr.shape)
#print(arr.size)
#print(arr.dtype)

print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [ ]:
#reshaping arrays

arr=np.array([1,2,3,4,5,6])

reshaped=arr.reshape(2,3)
print(reshaped)

#flatten
flat=reshaped.flatten()
print(flat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
def func(b,c):
 print(b*c)

a=23
b=25
func(a,b)

575


In [ ]:
# Array operations,indexing,slicing,reshaping
#indexing

#this is for 1D
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

#this is for 2D
matrix=np.array(([1,2,3],
                  [4,5,6]))
print(matrix[0,1])
print(matrix[1,2])

10
40
2
6


In [ ]:
#slicing in array

#this is for 1d slicing
arr=np.array([10,20,30,40,50])

print(arr[1:4])
print(arr[:3])
print(arr[1:2])

#this one is for 2d slicing

matrix=np.array(([1,2,3],
                 [4,5,6],
                 [7,8,9]))

print(matrix[:3,:2])
print(matrix[1:,1:])
print(matrix[::2,::2])

[20 30 40]
[10 20 30]
[20]
[[1 2]
 [4 5]
 [7 8]]
[[5 6]
 [8 9]]
[[1 3]
 [7 9]]


In [ ]:
#this is for 1d array
a=np.array([1,2,3]),
b=np.array([1,2,3])

print(a+b)
print(a+b)



a=np.array(([1,2],
            [3,4]))

b=np.array(([5,6],
            [7,8]))

print(a+b)

# matrix maltiplication

# matrix addition

a=np.array(([1,2],
            [3,4]))

b=np.array(([5,6],
            [7,8]))
#1,2.5,6. 19  22
#3,4,7,8.  43

#print(a+b)
print(a@b)

[[2 4 6]]
[[2 4 6]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
